app/Http/routes.php
<?php
/**
 * Public Page Routes
 */
Route::get('/', ['as' => 'home', 'uses' => 'HomeController@index']);
Route::post('/enquiry', 'EnquiryController@newEnquiry');

// Venue Register
Route::get('/register', 'VenueController@index');
Route::post('/register', 'VenueController@register');
Route::get('/register/{id}/{activation}', 'VenueController@activate');

// Pages
Route::get('/about', 'HomeController@about');
Route::get('/faqs', 'HomeController@faqs');

Route::get('/contact', 'HomeController@contact');
Route::post('/contact', 'HomeController@contactsubmit');
// Route::get('/blog', 'BlogController@viewAllPosts');
// Route::get('/blog/{slug}', 'BlogController@viewSinglePost');

// Feed
Route::get('/feed', 'FeedController@index');
Route::get('/feed/{id}', 'FeedController@getLeadLandingPage');

// Sitemap
Route::get('/xml_sitemap', 'HomeController@sitemap');


// Login 
Route::group(['middleware' => 'guest'], function() {
	Route::get('/login', 'AccountsController@login');
	Route::post('/login', 'AccountsController@auth');
});

Route::get('/logout', 'AccountsController@logout');

/**
 * Venue Admin Routes
 */
Route::group(['middleware' => ['auth', 'venue']], function() {
	
	Route::get('/venue', ['as' => 'venue_admin', 'uses' => 'VenueController@dashboard']);
	
	Route::get('/my_leads', ['as' => 'my_leads', 'uses' => 'EnquiryController@allEnquiries']);
	Route::get('/my_leads/lead/{id}', 'EnquiryController@enquiryDetail');

	Route::post('/purchase_quote', 'QuotesController@purchase');
	Route::get('/quote', ['as' => 'quote', 'uses' => 'QuotesController@getQuotes']);
	Route::get('/quote/{id}', 'QuotesController@singleQuote');
	Route::post('/sendQuote', 'QuotesController@sendQuote');
	
	Route::get('/my_venues', 'VenueController@venues');
	Route::post('/my_venues/update/{id}', 'VenueController@updateVenue');
	
	Route::get('/my_accounts', 'AccountsController@account');
		Route::post('/credits/twenty', 'BillingController@twentyCredits');
		Route::post('/credits/fourty', 'BillingController@fourtyCredits');
		Route::post('/credits/sixty', 'BillingController@sixtyCredits');
		Route::post('/credits/onehundred', 'BillingController@oneHundredCredits');
	Route::post('/buy_subscription', 'BillingController@subscribe');
	
	Route::get('/venue_reports', 'AccountsController@reports');
	
	Route::get('/venue_profile', 'AccountsController@profile');
	
	Route::post('/venue_profile/edit', 'AccountsController@updateProfile');
});

/**
 * Customer Admin Routes
 */
Route::group(['middleware' => ['auth','customer']], function() {
	
	Route::get('/user/quotes', ['as' => 'user_admin', 'uses' => 'CustomerController@listQuotes']);
	Route::get('/user/quotes/{id}', 'CustomerController@viewQuotes');

});

/**
 * Venue Detective Admin Routes
 */
Route::group(['middleware' => ['auth','admin']], function() {
	Route::get('/admin', ['as' => 'vendec_admin', 'uses' => 'AdminController@dashboard']);

	Route::get('/admin/venues', 'AdminController@venues');

	Route::get('/admin/users', 'AdminController@users');

	Route::get('/admin/reports', 'AdminController@reports'); 

});

app/Models/Quote.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Traits\Filterable;

class Quote extends Model
{
    
    use Filterable;

	
    /*****************************
     * Relationships
     ******************************/

	/**
	 * A quote is for a specific lead
	 * @return [type] [description]
	 */
    public function lead()
    {
    	return $this->belongsTo('App\Models\Lead', 'lead_id');
    }


    /********************************
     * Accessors & Mutators
     */

    public function getDisabledAccessAttribute($value)
    {
        switch ($value) {
            case '0':
                return "No";
                break;
            case '1':
                return "Yes";
            default:
                return "No";
                break;
        }
    }

    /*******************************
     * Scopes
     *******************************/

    public function scopeLeadsAwaitingQuotesForUser($query, $id)
    {
        return $query->where('user_id', $id)
                     ->where('awaiting_quote', 1);
                        
    }

    public function scopeLeadsQuotedForUser($query, $id)
    {
        return $query->where('user_id', $id)
                     ->where('quoted', 1);
    }
    

}

app/Http/Controllers/CustomerController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Lead;
use App\Models\Quote;
use App\Models\User;
use Sentinel;

class CustomerController extends Controller
{
    

    /**
     * View the customers Enquiries
     * @return [type] [description]
     */
    public function listQuotes()
    {
    	$user = User::find(Sentinel::getUser()->id);
    	$quotes = Lead::where('customer_id', '=', $user->id)->get();
        return view('customer.quotes')->with(['quotes' => $quotes]);
    }

    
    /**
     * View the Quotes given for a customers enquiry
     * Include a summary of the Enquiry
     * @param  $id Quote ID
     */
    public function viewQuotes($id)
    {
        $leadSummary = Lead::find($id);
        $quotes = Quote::where('lead_id', '=', $id)->get();
        return view('customer.quote')->with(['quotes' => $quotes, 'leadSummary' => $leadSummary]);
    }


}

resources/views/customer/quote.blade.php
@extends('layouts.master')

@section('content')
<div class="row">
	<div class="small-12 column Admin_Panel">
		<div class="Panel small-12 medium-8 large-9 columns">
				<div class="Panel_Title Grey_Gradient">
					<span><a href="#"></a></span>
					<h4>Quoted Enquiries - Ref: {{ $leadSummary->id }}</h4>
				</div>
				<div class="Panel_Content">
					<div class="callout secondary">
					 <h5>Quote Summary</h5>
					 <p>Use this table to review the quotes you have received for this enquiry. More details for each quote can be found below, where you can also accept or decline the quote. Once a quote has been accepted, the details of the venue will be revealed. </p>
						<table class="User_Quote_Summary_Table">
							<thead>
								<tr>
									<th>Venue</th>
									<th>Quote</th>
									<th></th>
									<th></th>
									<th></th>
									<th></th>
									<th></th>
								</tr>
							</thead>
							<tbody>	
							@foreach ($quotes as $index => $quote)				
								<tr>
									<td>{{ $index+1 }}</td>
									<td>£{{ $quote->total_cost }}</td>
									<td></td>
									<td><a href="#">Click Here to read all the details</a></td>
									<td></td>								
									<td></td>
									<td></td>
								</tr>
							@endforeach
							</tbody>
						</table>
					</div>

					<div class="callout warning">
						
						<h5>Enquiry Summary</h5>
						<table class="User_Quotes_Table">
							<tbody>
								<tr>
									<td>Reference Number:</td>
									<td>{{ $leadSummary->id }}</td>
								</tr>
								<tr>
									<td>Event Type:</td>
									<td>{{ $leadSummary->eventType->name }}</td>
								</tr>
								<tr>
									<td>Event Date:</td>
									<td>{{ date('F d, Y', strtoTime($leadSummary->dates->first()->date)) }}</td>
								</tr>
								<tr>
									<td>Date/Time Submitted:</td>
									<td>{{ date('F d, Y', strtotime($leadSummary->created_at)) }}</td>
								</tr>
								<tr>
									<td>Estimated Budget:</td>
									<td>£{{ $leadSummary->budget }}</td>
								</tr>
							</tbody>
						</table>

					</div>

					<div class="callout secondary">
						<ul class="tabs" data-tabs id="quote-tabs">
						    @foreach ($quotes as $index => $quote)
						  		<li class="tabs-title Enquiries_Tab"><a href="#panel{{ $index+1 }}" aria-selected="true">Venue {{ $index+1 }} - £{{ $quote->total_cost }}</a></li>
							@endforeach	
						</ul>
						<div class="tabs-content Enquiries_Tab_Content_Block" data-tabs-content="quote-tabs">
						  
							@foreach ($quotes as $index => $quote)
								<div class="tabs-panel" id="panel{{ $index+1}}">
								  <h4>Venue {{ $index+1 }}</h4>

								  <h5>Venue Capacity</h5>
								  <p>{{ $quote->min_attendance }} - {{ $quote->max_attendance }}</p>		
								  
								  <h5>Disabled Access Available?</h5>
								  <p>{{ $quote->disabled_access }}</p>
	
								  <h5>Quote Includes</h5>
								  <p>{!! $quote->included_in_cost !!}</p>

								  <h5>Extras</h5>
								  <p>{!! $quote->extras !!}</p>

								  <h5>Quote Breakdown</h5>
								  <p>{!! $quote->price_breakdown !!}</p>

								  <h5>Why Choose this Venue?</h5>
								  <p>{!! $quote->plug !!}</p>

								  <h5>Notes</h5>
								  <p>{!! $quote->notes !!}</p>

								  <h5>Total Quote: £{{ $quote->total_cost }}</h5>

								</div>
							@endforeach							  
						  	
						</div>
					</div>

				</div>

		</div>
	</div>
</div>

@endsection

@section('scripts')
<script type="text/javascript">
	(function(){
		$('ul#quote-tabs li:nth-child(1)').addClass('is-active');
		$('div.tabs-content div:nth-child(1)').addClass('is-active');
	})();
</script>
@endsection

resources/views/customer/quotes.blade.php
@extends('layouts.master')

@section('content')
<div class="row">
		<div class="small-12 column Admin_Panel">
			
			<div class="Panel small-12 columns">
				<div class="Panel_Title Grey_Gradient">
					<span><a href="#"></a></span>
					<h4>My Enquiries</h4>
				</div>
				<div class="Panel_Content">
					<table>
						<thead>
							<tr>
								<th>Ref</th>
								<th>Event Type</th>
								<th>Event Date</th>
								<th>Date Sent</th>
								<th>Location</th>
								<th>Budget</th>
								<th>Quotes Received</th>
							</tr>
						</thead>
						<tbody>
						@foreach ($quotes as $quote)
							<tr>
								<td>{{ $quote->id }}</td>
								<td>{{ $quote->eventType->name }}</td>
								<td>{{ date('F d, Y', strtoTime($quote->dates->first()->date)) }}</td>
								<td>{{ date('F d, Y', strtoTime($quote->created_at)) }}</td>
								<td>{{ $quote->location }}</td>								
								<td>£ {{ $quote->budget }}</td>
								<td>3</td>
								<td><a href="/user/quotes/{{ $quote->id }}">View</a></td>
							</tr>
						@endforeach
						</tbody>
					</table>
				</div>
			</div>

		</div>
</div>

@endsection